# Generated by Django 6.0.7 on 2026-07-12 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_communitymessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communitymessage',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='communitymessage',
            old_name='user',
            new_name='sender',
        ),
    ]
