# Generated by Django 6.0.7 on 2026-07-16 11:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_communitymessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
