# Generated by Django 6.0.7 on 2026-07-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='country_flag',
            field=models.CharField(default='🇮🇳', max_length=10),
        ),
    ]
