# Generated by Django 6.0.7 on 2026-07-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_comments_count_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='Travel', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='other_category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
