# Generated by Django 6.0.7 on 2026-07-09 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='country_flag',
        ),
    ]
