# Generated by Django 6.0.7 on 2026-07-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_comments_count_alter_postlike_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Sports', 'Sports'), ('Travel', 'Travel'), ('Technology', 'Technology'), ('Food', 'Food'), ('Education', 'Education'), ('Health', 'Health'), ('Business', 'Business'), ('Lifestyle', 'Lifestyle'), ('Entertainment', 'Entertainment'), ('Other', 'Other')], max_length=100),
        ),
    ]
