# Generated by Django 6.0.7 on 2026-07-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_post_community_post_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Sports', 'Sports'), ('Travel', 'Travel'), ('Food', 'Food'), ('Business', 'Business'), ('Technology', 'Technology'), ('Gaming', 'Gaming'), ('Photography', 'Photography'), ('Education', 'Education'), ('Music', 'Music'), ('Movies', 'Movies'), ('Health', 'Health'), ('Lifestyle', 'Lifestyle'), ('Other', 'Other')], max_length=100),
        ),
    ]
