# Generated by Django 6.0.7 on 2026-07-12 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_post_notification_url_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='related_id',
        ),
    ]
