# Generated by Django 6.0.7 on 2026-07-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_notification_related_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'Follow'), ('blog', 'Blog'), ('like', 'Like'), ('comment', 'Comment'), ('community', 'Community')], max_length=20),
        ),
    ]
